### PR TITLE
Hassan/shadcn

### PR DESCRIPTION
**Pull request by HassanAlabdulal**
I've developed a multi-step registration form with advanced validation. 
UI enhancements and minor tweaks are pending. 
Backend integration is prepped and ready.

### CODE REVIEW

**Comment by HassanAlabdulal** [comment]
close #18

**Comment by HassanAlabdulal** [comment]
Everything related to the form is ready, I also wrote comments and cleaned the code as much as I could (:

**Review by Mi3liX9 — APPROVED** [review]
Perfect! 🔥🔥

**Review by Mi3liX9 — APPROVED** [review]
approved

**Pull request merged**
